name: Standard workflow
run-name: ${{github.actor}} is running CI pipeline
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: pip install -r requirements.txt

            - name: upload requirements
              uses: actions/upload-artifact@v4 
              with:
               name: requirements
               path: requirements.txt
    py-test:
        needs: build 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: download requirements
              uses: actions/download-artifact@v4
              with: 
                name: requirements
            - name: run instalation of dependencies
              run: pip install -r requirements.txt

            - name: run pytest
              run: pytest -v
    docker-build:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: download requirements
              uses: actions/download-artifact@v4
              with: 
                name: requirements
            
            - name: run instalation of dependencies
              run: pip install -r requirements.txt
            - run: docker build -t api-build . 
            - run: docker run --name python-build -d -p 5000:5000 api-build
            - run: |
                for i in {1..6); do
                    curl http://0.0.0.0:5000/ && break || sleep 5
                done
            - run: curl http://0.0.0.0:5000/
            - run: curl http://0.0.0.0:5000/stats 
            - run: curl http://0.0.0.0:5000/health 
            - run: docker stop python-build
            - run: docker remove python-build
            

    

